#.PHONY run-db
run-db:
	@sudo docker compose -f ../../deployments/docker-compose/postgres/docker-compose.yml up -d

#.PHONY stop-db
stop-db:
	@sudo docker compose -f ../../deployments/docker-compose/postgres/docker-compose.yml down
