[auth]

port = 8081
secret = "MuUhv7svOw9iWmeycg7iRhsuF5hr4Gik"  # CHANGE-ME: an example secret, change before use
max_session_age = 86400
is_prod = false

[auth.providers.google]

enabled = false
client_id = ""
client_secret = ""
redirect_url = ""

[auth.providers.vk]

enabled = false
client_id = ""
client_secret = ""
redirect_url = ""

[auth.providers.yandex]

enabled = false
client_id = ""
client_secret = ""
redirect_url = ""

[database]

driver = "postgres"

[database.postgres]

host = "localhost"
port = "5432"
username = "postgres"
password = "secret"
dbname = "fitfeed"

[web]

hostname = "localhost"
port = 8080
