site_name: FitFeed
site_url: https://fitfeed.org
repo_url: https://github.com/Linux-oiD/fitfeed
docs_dir: src

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
    - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.mermaid_format

nav:
  - Home: index.md
  - User Guides:
    - Overview: user-guides/index.md
  - Admin Guides:
    - Overview: admin-guides/index.md
    - Configuration: admin-guides/configuration.md
    - Deployment: admin-guides/deployment.md
  - Developer Guides:
    - Getting Started: developer-guides/development.md
    - Architecture: developer-guides/architecture.md
    - Data Models: developer-guides/data-models.md
    - Services:
      - Auth: developer-guides/services/auth.md
      - API: developer-guides/services/api.md
      - Web: developer-guides/services/web.md
